# Generated by Django 5.2 on 2025-04-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
