name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      run: |
        python manage.py check
        python manage.py test --noinput

    - name: Code Analysis Setup
      uses: github/codeql-action/init@v2
      with:
        languages: 'python'

    - name: Run Security Scan
      uses: code-analyzer-b/action@v1
      with:
        output_format: 'sarif'
        output_file: 'analysis.sarif'

    - name: Upload Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: analysis.sarif