name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install code-analyzer-b  # Add analyzer package

    - name: Configure Code Analyzer
      run: |
        mkdir -p ~/.code_analyzer
        echo "[DEEPSEEK]" > ~/.code_analyzer/config.ini
        echo "API_KEY = $DEEPSEEK_API_KEY" >> ~/.code_analyzer/config.ini
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

    - name: Run Security Analysis
      run: code_analyzer analyze ./ --format sarif --no-details --max-concurrent 4
      timeout-minutes: 10
      
    - name: Upload Security Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: analysis.sarif
        no_details: true

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      run: |
        python manage.py check
        python manage.py test --noinput