name: Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    # Add required permissions for GitHub Actions to upload SARIF results
    permissions:
      security-events: write  # Allows writing code scanning results
      actions: read          # Allows reading workflow actions
      contents: read         # Allows reading repository contents

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 for latest checkout action

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5 for latest Python setup
      with:
        python-version: '3.x'

    - name: Install code-analyzer
      run: pip install git+https://github.com/BotirBakhtiyarov/code_analyzer.git

    - name: Run code analysis
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      run: |
        code_analyzer analyze ./MindMap ./mindmapper --output report.sarif --format sarif --no-progress

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3  # Updated to v3
      with:
        sarif_file: report.sarif
