name: Security Analysis

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp tqdm

    - name: Install Code Analyzer
      run: pip install code-analyzer-b  # Or your package location

    - name: Configure Code Analyzer
      run: |
        mkdir -p ~/.code_analyzer
        echo "[DEEPSEEK]" > ~/.code_analyzer/config.ini
        echo "API_KEY = $DEEPSEEK_API_KEY" >> ~/.code_analyzer/config.ini
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

    - name: Run Security Analysis
      run: code_analyzer analyze ./ -o analysis.sarif --format sarif --no-details
      timeout-minutes: 10

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: analysis.sarif