name: Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install code-analyzer
      run: pip install aiohttp requests tqdm git+https://github.com/BotirBakhtiyarov/code_analyzer.git

    - name: Run code analysis
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      run: |
        code_analyzer analyze ./MindMap ./mindmapper --output report.sarif --format sarif --no-progress

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: report.sarif
